seo:
  title: Dataloop's Developers
  description: Drive your AI to production with end-to-end data management, automation pipelines and a quality-first data labeling platform.
  siteUrl: https://developers.dataloop.ai
  keywords: dataloop developer portal, api portal starter, api reference docs
  lang: en-US
showNextButton: true
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./assets/site/dl_logo-removebg-preview.png
  altText: Dataloop's Developers
toc:
  enable: true
oasDefinitions:
  restapi: ./resources/rest_api/openapi.json
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  - label: Dataloop Platform
    icon: ./assets/site/dataloop-logo.png
    href: https://console.dataloop.ai
  #  page: developer-portal/index.md

  - label: Developers and support docs
    icon: ./assets/site/dl_icon.png
    page: ./tutorials/tutorials.mdx
    #page: https://dataloop.ai/docs/welcome

  - label: SDK and CLI docs
    icon: ./assets/site/dataloop-logo.png
    page: ./resources/resources.mdx
    #href: https://sdk-docs.dataloop.ai/en/latest/index.html

  - search: true

footer:
  copyrightText: Copyright Â© Dataloop Ltd. 2023
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: 'https://dataloop.ai/terms/'
        - label: Privacy Notice
          href: 'https://dataloop.ai/privacy-policy/'
        - label: Cookie Notice
          href: 'https://dataloop.ai/privacy-policy/'
    - group: Support
      items:
        - label: FAQ
          href: 'https://dataloop.ai/docs/help-getting-started'
        - label: Contact us
          href: 'https://dataloop.ai/contact/'
